### ISSUE TITLE
handling filters: [dimension_name:...

### ISSUE THREAD

**Issue by weightwatchers-carlanderson** [joshtemple/lkml#35] opened 2020-06-19 13:31 UTC
It doesn't look like `lkml` likes the `filters: [name:...]` feature

 carl.anderson@nycCANDERSONmbp  ~/code/lookml  pip freeze | grep lkml
lkml==0.2.2

This example was taken from the looker docs:

 carl.anderson@nycCANDERSONmbp  ~/code/lookml  more filter.lkml
view: view_name {
  measure: field_name {
    filters: [dimension_name: "filter expression", dimension_name: "filter expression"]
  }
}

 carl.anderson@nycCANDERSONmbp  ~/code/lookml  lkml filter.lkml
Traceback (most recent call last):
  File "/opt/anaconda3/bin/lkml", line 8, in <module>
    sys.exit(cli())
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/__init__.py", line 99, in cli
    lookml = load(args.file)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/__init__.py", line 33, in load
    result = parser.parse()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 153, in parse
    return self.parse_expression()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 250, in parse_expression
    block = self.parse_block()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 322, in parse_block
    expression = self.parse_expression()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 250, in parse_expression
    block = self.parse_block()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 322, in parse_block
    expression = self.parse_expression()
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 89, in wrapper
    result = method(self, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/lkml/parser.py", line 267, in parse_expression
    f"Unable to find a matching expression for '{token.id}' "
SyntaxError: Unable to find a matching expression for ':' on line 3

**Comment by joshtemple** [comment] 2020-06-19 15:12
Thanks @weightwatchers-carlanderson, this is a duplicate of #32. I'll point you to the comments on #34 for a status update!

**Closed by joshtemple** 2020-06-19 15:12 UTC
