### ISSUE TITLE
Parser error when lookml view dimension labels contain double quotes 

### ISSUE THREAD

**Issue by YSArch** [joshtemple/lkml#50] opened 2021-02-07 17:22 UTC
File "/opt/python/lkml/parser.py", line 266, in parse_expression
Error: Unable to find a matching expression for '**<literal>**'

Even the double quotes are escaped.

dimension: CA_34__MONITOR { 
    sql: ${TABLE}."CA_34__MONITOR" ;;
    label: "**34\\" Monitor**"
    type: yesno 
}

**Comment by joshtemple** [comment] 2021-02-07 18:51
This looks like a bug. I’ll take a look tomorrow and see if I can push a
fix.

**Comment by joshtemple** [comment] 2021-02-10 20:59
Hey @YSArch, I'm not able to reproduce this on the latest version (1.1). What version of lkml are you using? Some double quoting issues were fixed in #46, so you might just need to update.

**Closed** 2021-02-18 17:35 UTC
